### ISSUE TITLE
Anyway to change priority for artwork

### ISSUE THREAD

**Issue by agugu2000** [seleuco/MAME4droid-2024#22]
I make my own bezels for mame.(a .lay file and .png)
But within the android version ,I had to use the lowest resolution for reshader to make  graphic better.This will  reduce the high-resolution of bezels.Also reshader runs on the artwork,making display not so clean.
 Any solutions? or any updates for future??
![20240203214840](https://github.com/seleuco/MAME4droid-2024/assets/119565781/2c7397bc-076f-487d-b1dd-903128ac3c59)
![20240203214833](https://github.com/seleuco/MAME4droid-2024/assets/119565781/a9d657d3-75b1-48ac-8228-9c6b57573743)

**Comment by seleuco** [comment]
First of all, congratulations on those artworks. They look very good and are awsome. :)

Currently, making artwork and shader effects compatible does not work very well. Artworks work best with overlay effects but you need a good gpu if you want to do it in high resolutions. Try it.

I've had to make some decisions regarding shader effects and they don't work perfectly with the artworks. In the short term I don't think I can improve since the shaders would have to be implemented internally into the MAME rendering itself and that would take me a long time and I also think I would encounter quite a few problems.

The most plausible solution would be to try to use Mame's own bgfx system but important things like the auto rotate  would be lost and even then I am not sure without spending time what real compatibility I would find.

At the moment I prefer to improve other aspects that give results faster.

**Comment by agugu2000** [comment]
> Great i found this information, i thought i did something wrong. I think best is to use it without artwork, as shader effects does such a better job then the internal overlay effects, even the scanline looks bad. but if artwork/bezels is needed. i would recommend to set the emulator resolution to 640x480 without any filters, in that way the bezel will look fine and performance will also be good.
> 
> maybe a button inside the option would help, where to enable/disable bezel, and show a help text about it don't work with shaders enable. in that way it will not cause confusion.

Currently,i set the emulation resolution to 720p with a crt shader. It looks better now.
Actually scanlines make no sense on a cellphone oled(too small).All i need is just a curved display.In a high resolution,shader makes the monitor curved without scanlines,coincidently satisfied me,Ahaha
