### ISSUE TITLE
why netplay is removed in the 2024 version

### ISSUE THREAD

**Issue by NormanOu** [seleuco/MAME4droid-2024#58]
why netplay is removed in the 2024 version, will it come back in future versions?

**Comment by FlykeSpice** [comment]
Because alot of things have changed from the old mame version 139 (which the original mame4droid is based upon) and the current version.

It's a decade of difference, there was a major overhaul on the API since then, including the netplay, seleuco already spent a lot of time rewritting the frontend to work with the new API and probably didn't bother rewritting the netplay code aswell.

**Comment by seleuco** [comment]
correct. I also want to be able to update this version frequently.  The netplay code I developed in the old version meant very deep changes that would make it very difficult to have this version updated.
