### ISSUE TITLE
second stick support?

### ISSUE THREAD

**Issue by d8thstar** [seleuco/MAME4droid-2024#9]
thank you for this port!  any chance of adding high  tv stock support for twin stick shooters?

thanks!

**Comment by seleuco** [comment]
Are you talking about a second touch stick? Analog or digital? Tell me some example where a analog second stick is needed…stick digital games like robotron are already supported since stick is emulated with the four digital buttons. You can  customize like a diamond simulating a dpad. Also, if you Connect a controller supported natively by Mame4droid like Xbox one controller the righ stick is used for twin stick shooters. This emulator is touch designed mainly for arcade games that had at most 4 buttons except for the fighting buttons. For more complex games  it is better to connect a physical controller.

**Comment by d8thstar** [comment]
thanks for the response!

i’m new to android so please excuse my ignorance :). running on. pimax portal and was hoping that right stick could be used as a second stick instead of buttons.

i’ll play around with pimax’s control remapping and see if i can get it working.

thanks again for the awesome port!

**Comment by seleuco** [comment]
Yes. Pimax portal is not officially supported that why is not working the second stick. Only some controllers like Xbox one controller has full support including analog stick and triggers. In your case, you can only use it with digital inputs and without second stick but that is not a big problem with arcade games in general. You should define your buttons at Mame4droid “define keys” option on game controller section.  To play twin stick games use buttons. It’s works well when you get it.
